sources:
  my-mongodb:
    kind: mongodb
    uri: "mongodb://mongo:password@mongodb:27017/test?authSource=admin&retryWrites=true&w=majority"
tools:
  get_user_profile:
    kind: mongodb-find-one
    source: my-mongodb
    description: Retrieves a user's profile by their email address.
    database: test
    collection: user
    filterPayload: |
      { "email": {{json .email}} }
    filterParams:
      - name: email
        type: string
        description: The email address of the user to find.
    