sources:
  my-mongodb:
    kind: mongodb
    uri: ${MONGODB_URI}
  my-supabase:
    kind: http
    baseUrl: ${SUPABASE_URL}
    headers:
      apikey: ${SUPABASE_API_KEY}
      Authorization: "Bearer ${SUPABASE_API_KEY}"
tools:
  get_user_profile:
    kind: mongodb-find-one
    source: my-mongodb
    description: Retrieves a user's profile by their email address.
    database: test
    collection: user
    filterPayload: |
      { "email": {{json .email}} }
    filterParams:
      - name: email
        type: string
        description: The email address of the user to find.
  get_product_by_ref:
    kind: http
    source: my-supabase
    description: Fetch product details from Supabase by ref
    path: "/rest/v1/products_new2?select=*&ref=eq.22361020" 
    method: GET
  get_product_by_barcode:
    kind: http
    source: my-supabase
    description: Fetch product details from Supabase by barcode
    path: "/rest/v1/products_new2?select=*&barcode=eq.3664142565604"  
    method: GET
  